// 默认演示引擎模板：手工校验过的结构化 JSON，无 API Key 时可直接演示
import type { KnowledgeJSON } from '../types/knowledge';

export interface DemoTemplate {
  id: string;
  name: string;
  subject: string;
  knowledge: KnowledgeJSON;
}

export const TEMPLATES: DemoTemplate[] = [
  {
    id: 'tpl-quadratic',
    name: '二次函数参数变化',
    subject: '数学',
    knowledge: {
      type: 'quadratic',
      title: '二次函数 y = ax² + bx + c',
      formula: 'y = ax² + bx + c',
      subject: '数学',
      parameters: {
        a: { label: 'a（开口方向/宽窄）', min: -5, max: 5, step: 0.1, value: 1, effect: 'a>0 开口向上，a<0 开口向下，|a| 越大开口越窄' },
        b: { label: 'b（对称轴位置）', min: -10, max: 10, step: 0.1, value: -3, effect: '改变对称轴 x = -b/2a 的位置' },
        c: { label: 'c（y 轴截距）', min: -10, max: 10, step: 0.1, value: 2, effect: '图像整体上下平移' },
      },
      understanding: '这是一个二次函数模型，演示参数 a、b、c 对抛物线开口方向、宽窄、对称轴与顶点位置的影响。',
      rules: ['a>0 开口向上，a<0 开口向下', '|a| 越大开口越窄', '对称轴为 x = -b/(2a)', 'c 是抛物线与 y 轴交点的纵坐标'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-linear',
    name: '一次函数斜率与截距',
    subject: '数学',
    knowledge: {
      type: 'linear',
      title: '一次函数 y = kx + b',
      formula: 'y = kx + b',
      subject: '数学',
      parameters: {
        k: { label: 'k（斜率）', min: -5, max: 5, step: 0.1, value: 1, effect: 'k>0 上升，k<0 下降，|k| 越大越陡' },
        b: { label: 'b（y 轴截距）', min: -8, max: 8, step: 0.1, value: 1, effect: '直线上下平移' },
      },
      understanding: '这是一次函数模型，演示斜率 k 与截距 b 对直线倾斜程度和位置的影响。',
      rules: ['k>0 时 y 随 x 增大而增大', 'k<0 时 y 随 x 增大而减小', 'b 是直线与 y 轴交点的纵坐标'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-trig',
    name: '正弦函数图象变换',
    subject: '数学',
    knowledge: {
      type: 'trig',
      title: '三角函数 y = A·sin(ωx + φ) + b',
      formula: 'y = A·sin(ωx + φ) + b',
      subject: '数学',
      parameters: {
        A: { label: 'A（振幅）', min: -3, max: 3, step: 0.1, value: 1.5, effect: '控制波峰波谷的高度' },
        omega: { label: 'ω（角频率）', min: 0.2, max: 4, step: 0.1, value: 1, effect: 'ω 越大周期越短' },
        phi: { label: 'φ（初相）', min: -3.14, max: 3.14, step: 0.01, value: 0, effect: '控制图象左右平移' },
        b: { label: 'b（纵向平移）', min: -2, max: 2, step: 0.1, value: 0, effect: '平衡位置上下移动' },
      },
      understanding: '这是正弦型函数模型，演示振幅 A、角频率 ω、初相 φ、纵向平移 b 对波形的影响。',
      rules: ['振幅为 |A|', '周期 T = 2π/|ω|', '图象向左平移 φ/ω 个单位', '平衡位置为 y = b'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-circle',
    name: '圆的标准方程',
    subject: '数学',
    knowledge: {
      type: 'circle',
      title: '圆 (x−h)² + (y−k)² = r²',
      formula: '(x−h)² + (y−k)² = r²',
      subject: '数学',
      parameters: {
        h: { label: 'h（圆心横坐标）', min: -8, max: 8, step: 0.1, value: 1, effect: '圆左右平移' },
        k: { label: 'k（圆心纵坐标）', min: -5, max: 5, step: 0.1, value: 0.5, effect: '圆上下平移' },
        r: { label: 'r（半径）', min: 0.5, max: 6, step: 0.1, value: 3, effect: '控制圆的大小' },
      },
      understanding: '这是圆的标准方程模型，演示圆心 (h, k) 与半径 r 对圆的位置和大小的影响。',
      rules: ['圆心为 (h, k)，半径为 r', 'r 必须大于 0', '圆上任意点到圆心的距离等于 r'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-newton',
    name: '牛顿第二定律 F=ma',
    subject: '物理',
    knowledge: {
      type: 'newton_second_law',
      title: '牛顿第二定律 F = ma',
      formula: 'F = ma',
      subject: '物理',
      parameters: {
        m: { label: 'm（质量）', min: 0.5, max: 10, step: 0.1, value: 2, unit: ' kg', effect: 'a 不变时，F 与 m 成正比' },
        a: { label: 'a（加速度）', min: -5, max: 5, step: 0.1, value: 1.5, unit: ' m/s²', effect: 'm 不变时，F 与 a 成正比' },
      },
      understanding: '这是牛顿第二定律模型，演示质量 m 与加速度 a 变化时合力 F 的变化。',
      rules: ['F = ma，力等于质量乘以加速度', '力的方向与加速度方向一致', '质量是物体惯性大小的量度'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-quadratic-vertex',
    name: '抛物线顶点式',
    subject: '数学',
    knowledge: {
      type: 'quadratic',
      title: '抛物线顶点与对称轴',
      formula: 'y = a(x − h)² + k（展开为 y = ax² + bx + c）',
      subject: '数学',
      parameters: {
        a: { label: 'a（开口方向/宽窄）', min: -4, max: 4, step: 0.1, value: -0.8, effect: 'a<0 时开口向下，有最大值' },
        b: { label: 'b（一次项系数）', min: -8, max: 8, step: 0.1, value: 2, effect: '影响对称轴位置' },
        c: { label: 'c（常数项）', min: -6, max: 6, step: 0.1, value: 1, effect: '图像上下平移' },
      },
      understanding: '这是开口向下的抛物线，演示顶点（最高点）与对称轴随参数变化的规律。',
      rules: ['a<0 时抛物线开口向下，顶点为最高点', '顶点坐标为 (-b/2a, (4ac-b²)/4a)', '对称轴经过顶点且垂直于 x 轴'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-rect-area',
    name: '矩形面积公式',
    subject: '数学',
    knowledge: {
      type: 'rect_area',
      title: '矩形面积 S = a×b',
      formula: 'S = a × b',
      subject: '数学',
      parameters: {
        a: { label: 'a（长）', min: 1, max: 12, step: 0.1, value: 6, effect: '改变矩形的长，面积与长成正比' },
        b: { label: 'b（宽）', min: 1, max: 12, step: 0.1, value: 4, effect: '改变矩形的宽，面积与宽成正比' },
      },
      understanding: '这是矩形面积模型，通过单位方格的计数演示面积 S 等于长 a 与宽 b 的乘积。',
      rules: ['矩形面积 S = a×b', '宽不变时，面积与长成正比', '长宽互换，面积不变（乘法交换律）'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-triangle-area',
    name: '三角形面积·等底等高',
    subject: '数学',
    knowledge: {
      type: 'triangle_area',
      title: '三角形面积 S = ½×底×高',
      formula: 'S = ½ × base × height',
      subject: '数学',
      parameters: {
        base: { label: '底', min: 1, max: 12, step: 0.1, value: 8, effect: '改变底边长度，面积与底成正比' },
        height: { label: '高', min: 1, max: 10, step: 0.1, value: 5, effect: '改变高，面积与高成正比' },
        offset: { label: '顶点偏移', min: -6, max: 6, step: 0.1, value: 2, effect: '左右移动顶点，面积不变' },
      },
      understanding: '这是三角形面积模型，演示面积等于底乘高的一半，且顶点在与底平行的直线上移动时面积不变。',
      rules: ['三角形面积 S = ½×底×高', '等底等高的三角形面积相等', '顶点沿底的平行线移动时，形状改变但面积不变'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-parallelogram-area',
    name: '平行四边形割补',
    subject: '数学',
    knowledge: {
      type: 'parallelogram_area',
      title: '平行四边形面积 S = 底×高',
      formula: 'S = base × height',
      subject: '数学',
      parameters: {
        base: { label: '底', min: 1, max: 12, step: 0.1, value: 8, effect: '改变底边长度，面积与底成正比' },
        height: { label: '高', min: 1, max: 10, step: 0.1, value: 4, effect: '改变高，面积与高成正比' },
        slant: { label: '倾斜偏移', min: -6, max: 6, step: 0.1, value: 3, effect: '改变倾斜程度，面积不变' },
      },
      understanding: '这是平行四边形面积模型，通过割补法把一端的三角形平移到另一端，拼成等面积的矩形。',
      rules: ['平行四边形面积 S = 底×高', '割补后得到的矩形与原平行四边形面积相等', '倾斜程度改变时，只要底和高不变，面积就不变'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-circle-area',
    name: '圆面积与割圆术',
    subject: '数学',
    knowledge: {
      type: 'circle_area',
      title: '圆的面积与割圆术',
      formula: 'S = πr²',
      subject: '数学',
      parameters: {
        r: { label: 'r（半径）', min: 0.5, max: 6, step: 0.1, value: 3, effect: '改变圆的大小，面积与 r² 成正比' },
        n: { label: 'n（割圆边数）', min: 3, max: 64, step: 1, value: 6, effect: '内接正多边形边数越多，面积越接近圆面积' },
      },
      understanding: '这是圆面积模型，用刘徽割圆术的思想：以内接正 n 边形的面积逼近圆的面积，演示极限过程。',
      rules: ['圆的面积 S = πr²', '内接正多边形的边数 n 越大，其面积越接近圆面积', '割之弥细，所失弥少，割之又割，以至于不可割，则与圆合体'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-exponential',
    name: '指数增长 y=2^x',
    subject: '数学',
    knowledge: {
      type: 'exponential',
      title: '指数函数 y = a^x（增长）',
      formula: 'y = a^x',
      subject: '数学',
      parameters: {
        a: { label: 'a（底数）', min: 0.1, max: 4, step: 0.05, value: 2, effect: 'a>1 时函数单调递增，a 越大增长越快' },
      },
      understanding: '这是指数增长模型，演示底数 a>1 时函数值随 x 爆炸式增长的特征。',
      rules: ['a>1 时 y = a^x 单调递增', '图象恒过定点 (0, 1)', 'x 越大增长越快，呈爆炸式增长'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-exponential-decay',
    name: '指数衰减 y=0.5^x',
    subject: '数学',
    knowledge: {
      type: 'exponential',
      title: '指数函数 y = a^x（衰减）',
      formula: 'y = a^x（0 < a < 1）',
      subject: '数学',
      parameters: {
        a: { label: 'a（底数）', min: 0.1, max: 4, step: 0.05, value: 0.5, effect: '0<a<1 时函数单调递减，a 越小衰减越快' },
      },
      understanding: '这是指数衰减模型，演示底数 0<a<1 时函数值随 x 增大而趋近于 0 的特征，如半衰期。',
      rules: ['0<a<1 时 y = a^x 单调递减', '图象恒过定点 (0, 1)', 'x 越大函数值越接近 0，但永远大于 0'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-derivative',
    name: '导数的几何意义',
    subject: '数学',
    knowledge: {
      type: 'derivative',
      title: '导数的几何意义',
      formula: "f'(x₀) = lim(h→0) [f(x₀+h) − f(x₀)] / h",
      subject: '数学',
      parameters: {
        a: { label: 'a（二次项系数）', min: -2, max: 2, step: 0.1, value: 0.5, effect: '改变抛物线开口方向与宽窄' },
        b: { label: 'b（一次项系数）', min: -5, max: 5, step: 0.1, value: -2, effect: '改变对称轴位置' },
        c: { label: 'c（常数项）', min: -5, max: 5, step: 0.1, value: 1, effect: '图象上下平移' },
        x0: { label: 'x₀（切点横坐标）', min: -8, max: 8, step: 0.1, value: 3, effect: '移动切点位置' },
        h: { label: 'h（割线偏移）', min: -2, max: 2, step: 0.01, value: 1.5, effect: 'h 趋近 0 时割线趋近切线' },
      },
      understanding: '这是导数几何意义模型，演示当 h 趋近于 0 时，过 (x₀, f(x₀)) 与 (x₀+h, f(x₀+h)) 的割线趋近于切线，割线斜率的极限就是导数。',
      rules: ['导数 f\'(x₀) 是曲线在 x₀ 处切线的斜率', 'h→0 时割线斜率 [f(x₀+h)−f(x₀)]/h 的极限就是导数', '对 y=ax²+bx+c，f\'(x) = 2ax + b'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-uniform-motion',
    name: '匀变速直线运动 v-t 图',
    subject: '物理',
    knowledge: {
      type: 'uniform_motion',
      title: '匀变速直线运动 v-t 图面积',
      formula: 'v = v₀ + at，x = v₀t + ½at²',
      subject: '物理',
      parameters: {
        v0: { label: 'v₀（初速度）', min: 0, max: 20, step: 0.1, value: 2, unit: ' m/s', effect: 'v-t 图线的纵截距' },
        a: { label: 'a（加速度）', min: -5, max: 5, step: 0.1, value: 3, unit: ' m/s²', effect: 'v-t 图线的斜率' },
        t: { label: 't（时间）', min: 0, max: 10, step: 0.1, value: 4, unit: ' s', effect: '观察 0~t 内图线下方面积（位移）' },
      },
      understanding: '这是匀变速直线运动模型，v-t 图是一条倾斜直线，图线与时间轴围成的面积等于位移。',
      rules: ['v = v₀ + at，v-t 图是斜率为 a 的直线', 'v-t 图线下方的面积等于位移 x = v₀t + ½at²', 'a>0 匀加速，a<0 匀减速'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-free-fall',
    name: '自由落体运动',
    subject: '物理',
    knowledge: {
      type: 'uniform_motion',
      title: '自由落体运动',
      formula: 'v = gt，h = ½gt²',
      subject: '物理',
      parameters: {
        v0: { label: 'v₀（初速度）', min: 0, max: 20, step: 0.1, value: 0, unit: ' m/s', effect: '自由落体初速度为 0' },
        a: { label: 'g（重力加速度）', min: 1, max: 25, step: 0.1, value: 9.8, unit: ' m/s²', effect: '改变重力加速度大小' },
        t: { label: 't（下落时间）', min: 0, max: 10, step: 0.1, value: 2, unit: ' s', effect: '观察 t 时刻的速度与下落高度' },
      },
      understanding: '自由落体是初速度为 0、加速度为 g 的匀加速直线运动，是匀变速直线运动的特例。',
      rules: ['自由落体的初速度 v₀ = 0', '速度 v = gt，与时间成正比', '下落高度 h = ½gt²，与时间平方成正比'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-ohm-law',
    name: '欧姆定律',
    subject: '物理',
    knowledge: {
      type: 'ohm_law',
      title: '欧姆定律 I = U/R',
      formula: 'I = U / R',
      subject: '物理',
      parameters: {
        U: { label: 'U（电压）', min: 0, max: 12, step: 0.1, value: 6, unit: ' V', effect: 'R 不变时，I 与 U 成正比' },
        R: { label: 'R（电阻）', min: 1, max: 100, step: 1, value: 20, unit: ' Ω', effect: 'U 不变时，I 与 R 成反比' },
      },
      understanding: '这是欧姆定律模型，演示导体中的电流 I 与电压 U、电阻 R 的定量关系。',
      rules: ['I = U/R，电流等于电压除以电阻', '电阻不变时，电流与电压成正比', '电压不变时，电流与电阻成反比'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-projectile',
    name: '平抛运动',
    subject: '物理',
    knowledge: {
      type: 'projectile',
      title: '平抛运动',
      formula: 'x = v₀t，y = ½gt²',
      subject: '物理',
      parameters: {
        v0: { label: 'v₀（初速度）', min: 1, max: 30, step: 0.1, value: 10, unit: ' m/s', effect: '初速度越大，水平射程越远' },
        g: { label: 'g（重力加速度）', min: 1, max: 25, step: 0.1, value: 9.8, unit: ' m/s²', effect: 'g 越大，下落越快，轨迹越陡' },
        t: { label: 't（时间）', min: 0, max: 5, step: 0.05, value: 1.5, unit: ' s', effect: '观察 t 时刻小球的位置' },
      },
      understanding: '平抛运动可分解为水平方向的匀速直线运动和竖直方向的自由落体运动，合轨迹是抛物线。',
      rules: ['水平方向：x = v₀t，匀速直线运动', '竖直方向：y = ½gt²，自由落体运动', '平抛运动的轨迹是抛物线', '运动时间只由下落高度决定，与初速度无关'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-projectile-moon',
    name: '月球表面平抛',
    subject: '物理',
    knowledge: {
      type: 'projectile',
      title: '月球表面的平抛运动',
      formula: 'x = v₀t，y = ½g_月t²（g_月 ≈ 1.6 m/s²）',
      subject: '物理',
      parameters: {
        v0: { label: 'v₀（初速度）', min: 1, max: 30, step: 0.1, value: 10, unit: ' m/s', effect: '初速度越大，水平射程越远' },
        g: { label: 'g（月球重力加速度）', min: 1, max: 25, step: 0.1, value: 1.6, unit: ' m/s²', effect: '月球重力约为地球的 1/6，下落更慢' },
        t: { label: 't（时间）', min: 0, max: 5, step: 0.05, value: 3, unit: ' s', effect: '观察 t 时刻小球的位置' },
      },
      understanding: '月球表面重力加速度约为地球的 1/6，同样的初速度下，平抛物体下落更慢、射程更远。',
      rules: ['月球表面 g ≈ 1.6 m/s²，约为地球的 1/6', '重力越小，同样时间内下落高度越小', '平抛规律在月球上同样成立：水平匀速、竖直匀加速'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-bohr-oxygen',
    name: '氧原子玻尔模型',
    subject: '化学',
    knowledge: {
      type: 'bohr_atom',
      title: '氧原子的玻尔模型',
      formula: 'O：Z = 8，电子排布 2、6',
      subject: '化学',
      parameters: {
        Z: { label: 'Z（原子序数）', min: 1, max: 20, step: 1, value: 8, effect: '改变原子序数，观察核外电子分层排布' },
      },
      understanding: '这是玻尔原子模型，氧原子核内有 8 个质子，核外 8 个电子按 K、L 层排布为 2、6。',
      rules: ['原子序数 Z = 核内质子数 = 核外电子数', 'K 层最多容纳 2 个电子，L 层最多容纳 8 个电子', '氧原子最外层 6 个电子，容易得到 2 个电子形成稳定结构'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-bohr-sodium',
    name: '钠原子玻尔模型',
    subject: '化学',
    knowledge: {
      type: 'bohr_atom',
      title: '钠原子的玻尔模型',
      formula: 'Na：Z = 11，电子排布 2、8、1',
      subject: '化学',
      parameters: {
        Z: { label: 'Z（原子序数）', min: 1, max: 20, step: 1, value: 11, effect: '改变原子序数，观察核外电子分层排布' },
      },
      understanding: '这是玻尔原子模型，钠原子核外 11 个电子按 K、L、M 层排布为 2、8、1，最外层只有 1 个电子。',
      rules: ['电子按能量由低到高分层排布', '钠原子最外层 1 个电子，容易失去形成 Na⁺', '金属元素原子最外层电子数一般少于 4 个'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-chemical-balance',
    name: '氢氧燃烧配平',
    subject: '化学',
    knowledge: {
      type: 'chemical_balance',
      title: '化学方程式配平：氢气燃烧',
      formula: '2H₂ + O₂ = 2H₂O',
      subject: '化学',
      parameters: {
        h2: { label: 'H₂ 系数', min: 1, max: 6, step: 1, value: 2, effect: '改变氢气分子数' },
        o2: { label: 'O₂ 系数', min: 1, max: 6, step: 1, value: 1, effect: '改变氧气分子数' },
        h2o: { label: 'H₂O 系数', min: 1, max: 6, step: 1, value: 2, effect: '改变水分子数' },
      },
      understanding: '这是化学方程式配平模型，通过调整各物质的化学计量数，使反应前后各元素原子个数相等。',
      rules: ['配平依据：质量守恒定律，反应前后各元素原子个数相等', '2H₂ + O₂ = 2H₂O：氢原子 4=4，氧原子 2=2，配平正确', '化学计量数只能改动系数，不能改动化学式中的下标'],
      confidence: 1,
    },
  },
  {
    id: 'tpl-molecule-3d',
    name: '甲烷分子 3D 结构',
    subject: '化学',
    knowledge: {
      type: 'molecule_3d',
      title: '甲烷分子的 3D 结构',
      formula: 'CH₄',
      subject: '化学',
      variant: 'CH4',
      parameters: {
        rotX: { label: '绕 X 轴旋转', min: -180, max: 180, step: 1, value: -20, unit: '°', effect: '上下翻转观察分子空间构型' },
        rotY: { label: '绕 Y 轴旋转', min: -180, max: 180, step: 1, value: 30, unit: '°', effect: '左右旋转观察分子空间构型' },
      },
      understanding: '这是甲烷分子的球棍模型，1 个碳原子位于正四面体中心，4 个氢原子位于正四面体的 4 个顶点。',
      rules: ['CH₄ 分子呈正四面体构型', 'C−H 键之间的夹角均为 109°28′', '正四面体结构使分子对称，属于非极性分子'],
      confidence: 1,
    },
  },
];
